DROP TABLE IF EXISTS ADDRESS_ALIAS CASCADE;
DROP TABLE IF EXISTS ADDRESS_ALIAS_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS ADDRESS_CHANGE_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS ADDRESS_DEFAULT_GEOCODE CASCADE;
DROP TABLE IF EXISTS ADDRESS_DETAIL CASCADE;
DROP TABLE IF EXISTS ADDRESS_FEATURE CASCADE;
DROP TABLE IF EXISTS ADDRESS_MESH_BLOCK_2016 CASCADE;
DROP TABLE IF EXISTS ADDRESS_MESH_BLOCK_2021 CASCADE;
DROP TABLE IF EXISTS ADDRESS_SITE CASCADE;
DROP TABLE IF EXISTS ADDRESS_SITE_GEOCODE CASCADE;
DROP TABLE IF EXISTS ADDRESS_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS FLAT_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS GEOCODED_LEVEL_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS GEOCODE_RELIABILITY_AUT CASCADE;
DROP TABLE IF EXISTS GEOCODE_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS LEVEL_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS LOCALITY CASCADE;
DROP TABLE IF EXISTS LOCALITY_ALIAS CASCADE;
DROP TABLE IF EXISTS LOCALITY_ALIAS_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS LOCALITY_CLASS_AUT CASCADE;
DROP TABLE IF EXISTS LOCALITY_NEIGHBOUR CASCADE;
DROP TABLE IF EXISTS LOCALITY_POINT CASCADE;
DROP TABLE IF EXISTS MB_2016 CASCADE;
DROP TABLE IF EXISTS MB_2021 CASCADE;
DROP TABLE IF EXISTS MB_MATCH_CODE_AUT CASCADE;
DROP TABLE IF EXISTS PRIMARY_SECONDARY CASCADE;
DROP TABLE IF EXISTS PS_JOIN_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS STATE CASCADE;
DROP TABLE IF EXISTS STREET_CLASS_AUT CASCADE;
DROP TABLE IF EXISTS STREET_LOCALITY CASCADE;
DROP TABLE IF EXISTS STREET_LOCALITY_ALIAS CASCADE;
DROP TABLE IF EXISTS STREET_LOCALITY_ALIAS_TYPE_AUT CASCADE;
DROP TABLE IF EXISTS STREET_LOCALITY_POINT CASCADE;
DROP TABLE IF EXISTS STREET_SUFFIX_AUT CASCADE;
DROP TABLE IF EXISTS STREET_TYPE_AUT CASCADE;



